# Generated by Django 2.0.6 on 2019-01-24 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('num_stps', models.PositiveIntegerField(default=0)),
                ('stps_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
