# Generated by Django 2.0.6 on 2019-01-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iipinmotion', '0002_auto_20190124_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='predictedStps',
            new_name='predicted_Stps',
        ),
    ]
