# Generated by Django 2.0.6 on 2019-01-25 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iipinmotion', '0005_playerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPlays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_stps', models.PositiveIntegerField(default=0)),
                ('stps_date', models.DateField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iipinmotion.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='playerhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlayerHistory',
        ),
    ]
